apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.projectName }}-limit-range
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: {{ .Values.limits.defaultRequestCpu }}
        memory: {{ .Values.limits.defaultRequestMemory }}
      default:
        memory: {{ .Values.limits.defaultLimitMemory }}
      max:
        memory: {{ .Values.limits.maxMemory }}