apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.projectName }}
  labels:
    pod-security.kubernetes.io/enforce: {{ .Values.podSecurity.enforce }}
    pod-security.kubernetes.io/warn: {{ .Values.podSecurity.warn }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"