apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.projectName }}-quota
spec:
  hard:
    requests.cpu: {{ .Values.quota.requestsCpu }}
    requests.memory: {{ .Values.quota.requestsMemory }}
    limits.memory: {{ .Values.quota.limitsMemory }}
    persistentvolumeclaims: {{ .Values.quota.pvcs }}
    pods: {{ .Values.quota.pods }}